\hypertarget{classorg_1_1tzi_1_1use_1_1api_1_1_use_api_exception}{\section{org.\-tzi.\-use.\-api.\-Use\-Api\-Exception Class Reference}
\label{classorg_1_1tzi_1_1use_1_1api_1_1_use_api_exception}\index{org.\-tzi.\-use.\-api.\-Use\-Api\-Exception@{org.\-tzi.\-use.\-api.\-Use\-Api\-Exception}}
}
Inheritance diagram for org.\-tzi.\-use.\-api.\-Use\-Api\-Exception\-:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=2.000000cm]{classorg_1_1tzi_1_1use_1_1api_1_1_use_api_exception}
\end{center}
\end{figure}
\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\hyperlink{classorg_1_1tzi_1_1use_1_1api_1_1_use_api_exception_ab10281354c654e3d15742dbde9ee2036}{Use\-Api\-Exception} (String message)
\item 
\hyperlink{classorg_1_1tzi_1_1use_1_1api_1_1_use_api_exception_a4109e7307e6cdd14e6cb8b2159bfd050}{Use\-Api\-Exception} (String message, Throwable cause)
\end{DoxyCompactItemize}


\subsection{Detailed Description}
Exception thrown by the U\-S\-E A\-P\-I \begin{DoxyAuthor}{Author}
lhamann 
\end{DoxyAuthor}


Definition at line 29 of file Use\-Api\-Exception.\-java.



\subsection{Constructor \& Destructor Documentation}
\hypertarget{classorg_1_1tzi_1_1use_1_1api_1_1_use_api_exception_ab10281354c654e3d15742dbde9ee2036}{\index{org\-::tzi\-::use\-::api\-::\-Use\-Api\-Exception@{org\-::tzi\-::use\-::api\-::\-Use\-Api\-Exception}!Use\-Api\-Exception@{Use\-Api\-Exception}}
\index{Use\-Api\-Exception@{Use\-Api\-Exception}!org::tzi::use::api::UseApiException@{org\-::tzi\-::use\-::api\-::\-Use\-Api\-Exception}}
\subsubsection[{Use\-Api\-Exception}]{\setlength{\rightskip}{0pt plus 5cm}org.\-tzi.\-use.\-api.\-Use\-Api\-Exception.\-Use\-Api\-Exception (
\begin{DoxyParamCaption}
\item[{String}]{message}
\end{DoxyParamCaption}
)\hspace{0.3cm}{\ttfamily [inline]}}}\label{classorg_1_1tzi_1_1use_1_1api_1_1_use_api_exception_ab10281354c654e3d15742dbde9ee2036}


Definition at line 35 of file Use\-Api\-Exception.\-java.

\hypertarget{classorg_1_1tzi_1_1use_1_1api_1_1_use_api_exception_a4109e7307e6cdd14e6cb8b2159bfd050}{\index{org\-::tzi\-::use\-::api\-::\-Use\-Api\-Exception@{org\-::tzi\-::use\-::api\-::\-Use\-Api\-Exception}!Use\-Api\-Exception@{Use\-Api\-Exception}}
\index{Use\-Api\-Exception@{Use\-Api\-Exception}!org::tzi::use::api::UseApiException@{org\-::tzi\-::use\-::api\-::\-Use\-Api\-Exception}}
\subsubsection[{Use\-Api\-Exception}]{\setlength{\rightskip}{0pt plus 5cm}org.\-tzi.\-use.\-api.\-Use\-Api\-Exception.\-Use\-Api\-Exception (
\begin{DoxyParamCaption}
\item[{String}]{message, }
\item[{Throwable}]{cause}
\end{DoxyParamCaption}
)\hspace{0.3cm}{\ttfamily [inline]}}}\label{classorg_1_1tzi_1_1use_1_1api_1_1_use_api_exception_a4109e7307e6cdd14e6cb8b2159bfd050}


Definition at line 39 of file Use\-Api\-Exception.\-java.



The documentation for this class was generated from the following file\-:\begin{DoxyCompactItemize}
\item 
src/main/org/tzi/use/api/\hyperlink{_use_api_exception_8java}{Use\-Api\-Exception.\-java}\end{DoxyCompactItemize}
